# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Lessons.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1023, 863)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 501, 781))
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.pushButton_1 = QtWidgets.QPushButton(self.widget)
        self.pushButton_1.setObjectName("pushButton_1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButton_1)
        self.textEdit_6 = QtWidgets.QTextEdit(self.widget)
        self.textEdit_6.setObjectName("textEdit_6")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.textEdit_6)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pushButton_2)
        self.textEdit_2 = QtWidgets.QTextEdit(self.widget)
        self.textEdit_2.setObjectName("textEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.textEdit_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pushButton_3)
        self.textEdit_11 = QtWidgets.QTextEdit(self.widget)
        self.textEdit_11.setObjectName("textEdit_11")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.textEdit_11)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.pushButton_4)
        self.textEdit = QtWidgets.QTextEdit(self.widget)
        self.textEdit.setObjectName("textEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.textEdit)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.pushButton_5)
        self.textEdit_7 = QtWidgets.QTextEdit(self.widget)
        self.textEdit_7.setObjectName("textEdit_7")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.textEdit_7)
        self.pushButton_6 = QtWidgets.QPushButton(self.widget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.pushButton_6)
        self.textEdit_10 = QtWidgets.QTextEdit(self.widget)
        self.textEdit_10.setObjectName("textEdit_10")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.textEdit_10)
        self.pushButton_7 = QtWidgets.QPushButton(self.widget)
        self.pushButton_7.setObjectName("pushButton_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.pushButton_7)
        self.textEdit_5 = QtWidgets.QTextEdit(self.widget)
        self.textEdit_5.setObjectName("textEdit_5")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.textEdit_5)
        self.pushButton_8 = QtWidgets.QPushButton(self.widget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.pushButton_8)
        self.textEdit_3 = QtWidgets.QTextEdit(self.widget)
        self.textEdit_3.setObjectName("textEdit_3")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.textEdit_3)
        self.pushButton_10 = QtWidgets.QPushButton(self.widget)
        self.pushButton_10.setObjectName("pushButton_10")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.pushButton_10)
        self.textEdit_4 = QtWidgets.QTextEdit(self.widget)
        self.textEdit_4.setObjectName("textEdit_4")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.textEdit_4)
        self.pushButton_9 = QtWidgets.QPushButton(self.widget)
        self.pushButton_9.setObjectName("pushButton_9")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.pushButton_9)
        self.textBrowser = QtWidgets.QTextBrowser(self.widget)
        self.textBrowser.setObjectName("textBrowser")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.textBrowser)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(520, 0, 501, 781))
        self.widget1.setObjectName("widget1")
        self.gridLayout = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit_16 = QtWidgets.QTextEdit(self.widget1)
        self.textEdit_16.setObjectName("textEdit_16")
        self.gridLayout.addWidget(self.textEdit_16, 4, 1, 1, 1)
        self.textEdit_15 = QtWidgets.QTextEdit(self.widget1)
        self.textEdit_15.setObjectName("textEdit_15")
        self.gridLayout.addWidget(self.textEdit_15, 0, 1, 1, 1)
        self.textEdit_8 = QtWidgets.QTextEdit(self.widget1)
        self.textEdit_8.setObjectName("textEdit_8")
        self.gridLayout.addWidget(self.textEdit_8, 2, 1, 1, 1)
        self.textEdit_12 = QtWidgets.QTextEdit(self.widget1)
        self.textEdit_12.setObjectName("textEdit_12")
        self.gridLayout.addWidget(self.textEdit_12, 3, 1, 1, 1)
        self.textEdit_9 = QtWidgets.QTextEdit(self.widget1)
        self.textEdit_9.setObjectName("textEdit_9")
        self.gridLayout.addWidget(self.textEdit_9, 1, 1, 1, 1)
        self.textEdit_14 = QtWidgets.QTextEdit(self.widget1)
        self.textEdit_14.setObjectName("textEdit_14")
        self.gridLayout.addWidget(self.textEdit_14, 5, 1, 1, 1)
        self.textEdit_13 = QtWidgets.QTextEdit(self.widget1)
        self.textEdit_13.setObjectName("textEdit_13")
        self.gridLayout.addWidget(self.textEdit_13, 6, 1, 1, 1)
        self.textEdit_17 = QtWidgets.QTextEdit(self.widget1)
        self.textEdit_17.setObjectName("textEdit_17")
        self.gridLayout.addWidget(self.textEdit_17, 7, 1, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout.addWidget(self.pushButton_19, 8, 0, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout.addWidget(self.pushButton_14, 3, 0, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout.addWidget(self.pushButton_11, 0, 0, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout.addWidget(self.pushButton_15, 4, 0, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout.addWidget(self.pushButton_16, 5, 0, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout.addWidget(self.pushButton_13, 2, 0, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout.addWidget(self.pushButton_12, 1, 0, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout.addWidget(self.pushButton_18, 7, 0, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout.addWidget(self.pushButton_17, 6, 0, 1, 1)
        self.pushButton_20 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout.addWidget(self.pushButton_20, 9, 0, 1, 1)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.widget1)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.gridLayout.addWidget(self.textBrowser_2, 8, 1, 1, 1)
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.widget1)
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.gridLayout.addWidget(self.textBrowser_3, 9, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1023, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_1.setText(_translate("MainWindow", "Урок 1"))
        self.pushButton_2.setText(_translate("MainWindow", "Урок 2"))
        self.pushButton_3.setText(_translate("MainWindow", "Урок 3"))
        self.pushButton_4.setText(_translate("MainWindow", "Урок 4"))
        self.pushButton_5.setText(_translate("MainWindow", "Урок 5"))
        self.pushButton_6.setText(_translate("MainWindow", "Урок 6"))
        self.pushButton_7.setText(_translate("MainWindow", "Урок 7"))
        self.pushButton_8.setText(_translate("MainWindow", "Урок 8"))
        self.pushButton_10.setText(_translate("MainWindow", "Урок 10"))
        self.pushButton_9.setText(_translate("MainWindow", "Урок 9"))
        self.pushButton_19.setText(_translate("MainWindow", "Урок 19"))
        self.pushButton_14.setText(_translate("MainWindow", "Урок 14"))
        self.pushButton_11.setText(_translate("MainWindow", "Урок 11"))
        self.pushButton_15.setText(_translate("MainWindow", "Урок 15"))
        self.pushButton_16.setText(_translate("MainWindow", "Урок 16"))
        self.pushButton_13.setText(_translate("MainWindow", "Урок 13"))
        self.pushButton_12.setText(_translate("MainWindow", "Урок 12"))
        self.pushButton_18.setText(_translate("MainWindow", "Урок 18"))
        self.pushButton_17.setText(_translate("MainWindow", "Урок 17"))
        self.pushButton_20.setText(_translate("MainWindow", "Урок 20"))

